apiVersion: v2
name: samba
description: A Helm chart for Samba Time Machine on Kubernetes
icon: https://www.samba.org/samba/img/samba-logo.png
type: application
version: 3.0.5
appVersion: "smbd-only-latest"
